using BuildingBlocks.Domain.Common.Results;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using RealEstate.Domain.Entities;
using RealEstate.Domain.Enums;
using RealEstate.Domain.ValueObjects;

namespace RealEstate.Infrastructure.Data.Seeding;

// ---------------------------------------------------------------------------------------------
//  Runtime seeder for the RealEstate module.
//
//  WHY RUNTIME AND NOT modelBuilder.HasData(...)?
//    HasData bakes the rows into a migration, and you asked to own migrations yourself. It also
//    cannot call the domain factories, so it would write rows that bypass every invariant in
//    Property/Media/Location. This seeder goes through the real aggregates instead, so seeded
//    data is exactly as valid as data created through the API.
//
//  IDEMPOTENT: safe to run on every startup.
//    - PropertyTypes and Features are matched on Name (both are uniquely indexed).
//    - Properties are matched on Title. Title is NOT uniquely indexed in the database, so this
//      check is application-level only: if you rename a listing in SeedCatalog it will be
//      inserted again as a new row rather than updated. Nothing here ever updates or deletes.
//
//  ORDER MATTERS: Feature/PropertyType ids are generated by EF on insert (Entity.Id has no public
//  setter and their factories use the parameterless constructor), so they are Guid.Empty in
//  memory until SaveChanges runs. The seeder therefore saves the catalogs first and reads the
//  generated ids back before it can build PropertyFeature rows.
// ---------------------------------------------------------------------------------------------

public sealed class RealEstateDbSeeder
{
    private readonly RealEstateDbContext _db;
    private readonly ILogger? _log;

    public RealEstateDbSeeder(RealEstateDbContext db, ILogger? log = null)
    {
        _db = db;
        _log = log;
    }

    public async Task SeedAsync(CancellationToken ct = default)
    {
        var propertyTypeIds = await SeedPropertyTypesAsync(ct);
        var featureIds = await SeedFeaturesAsync(ct);

        // Areas run BEFORE properties so the backfill below always has a catalog to file into.
        await SeedAreasAsync(ct);

        await SeedPropertiesAsync(propertyTypeIds, featureIds, ct);
        await BackfillPropertyAreasAsync(ct);
        await SeedAgentsAsync(ct);
        await SeedDevelopmentsAsync(ct);
    }

    // -----------------------------------------------------------------------------------------
    //  areas  (matched on Slug — uniquely indexed, so this check is DB-backed)
    // -----------------------------------------------------------------------------------------
    private async Task SeedAreasAsync(CancellationToken ct)
    {
        var existing = await _db.Areas.Select(a => a.Slug).ToListAsync(ct);
        var known = new HashSet<string>(existing, StringComparer.Ordinal);
        var added = 0;

        foreach (var seed in AreaSeedCatalog.Areas)
        {
            if (known.Contains(seed.Slug))
                continue;

            var area = Must(
                Area.Create(seed.Name, seed.PhotoUrl, seed.Slug, seed.Intro),
                $"Area '{seed.Name}'");

            _db.Areas.Add(area);
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} area(s).", added);
        }
    }

    // -----------------------------------------------------------------------------------------
    //  Files any listing that still has no AreaId under an area, by keyword.
    //
    //  Only ever touches rows where AreaId IS NULL, so an area an admin picked by hand is never
    //  overwritten, and a listing an admin deliberately un-filed gets re-filed at most once —
    //  after which it keeps whatever the admin last set unless they clear it again.
    // -----------------------------------------------------------------------------------------
    private async Task BackfillPropertyAreasAsync(CancellationToken ct)
    {
        var unfiled = await _db.Properties.Where(p => p.AreaId == null).ToListAsync(ct);
        if (unfiled.Count == 0)
            return;

        var areaIdsBySlug = await _db.Areas.ToDictionaryAsync(a => a.Slug, a => a.Id, StringComparer.Ordinal, ct);
        var filed = 0;

        foreach (var property in unfiled)
        {
            var haystack = $"{property.Title} {property.Location.Street}";

            foreach (var (slug, keywords) in AreaSeedCatalog.BackfillKeywords)
            {
                if (!keywords.Any(k => haystack.Contains(k, StringComparison.OrdinalIgnoreCase)))
                    continue;

                if (!areaIdsBySlug.TryGetValue(slug, out var areaId))
                    break;      // area was deleted by an admin — leave the listing unfiled

                MustSucceed(property.AssignArea(areaId), $"filing '{property.Title}' under '{slug}'");
                filed++;
                break;          // first match wins — see AreaSeedCatalog.BackfillKeywords
            }
        }

        if (filed > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: filed {Count} listing(s) under an area.", filed);
        }
    }

    // -----------------------------------------------------------------------------------------
    //  developments  (matched on Slug — uniquely indexed, so this check is DB-backed)
    // -----------------------------------------------------------------------------------------
    private async Task SeedDevelopmentsAsync(CancellationToken ct)
    {
        var existing = await _db.Developments.Select(d => d.Slug).ToListAsync(ct);
        var known = new HashSet<string>(existing, StringComparer.Ordinal);
        var added = 0;

        foreach (var seed in DevelopmentSeedCatalog.Developments)
        {
            if (known.Contains(seed.Slug))
                continue;

            var development = Must(
                Development.Create(seed.Name, seed.AreaName, seed.DeliveryYear, seed.CoverImageUrl,
                                   seed.Slug, seed.Description, seed.UnitsCount, seed.DeveloperName,
                                   seed.StartingPrice, seed.PaymentPlan),
                $"Development '{seed.Name}'");

            _db.Developments.Add(development);
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} development(s).", added);
        }
    }

    // -----------------------------------------------------------------------------------------
    //  agents  (matched on Slug — uniquely indexed, so this check is DB-backed)
    // -----------------------------------------------------------------------------------------
    private async Task SeedAgentsAsync(CancellationToken ct)
    {
        var existing = await _db.Agents.Select(a => a.Slug).ToListAsync(ct);
        var known = new HashSet<string>(existing, StringComparer.Ordinal);
        var added = 0;

        foreach (var seed in AgentSeedCatalog.Agents)
        {
            if (known.Contains(seed.Slug))
                continue;

            var agent = Must(
                Agent.Create(seed.Name, seed.JobTitle, seed.PhotoUrl, seed.Slug,
                             seed.Phone, seed.WhatsApp, seed.Email, seed.Rating, seed.Bio),
                $"Agent '{seed.Name}'");

            _db.Agents.Add(agent);
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} agent(s).", added);
        }
    }

    // -----------------------------------------------------------------------------------------
    //  1. property types
    // -----------------------------------------------------------------------------------------
    private async Task<Dictionary<string, Guid>> SeedPropertyTypesAsync(CancellationToken ct)
    {
        var existing = await _db.PropertyTypes
            .Select(t => t.Name)
            .ToListAsync(ct);

        var known = new HashSet<string>(existing, StringComparer.OrdinalIgnoreCase);
        var added = 0;

        foreach (var seed in SeedCatalog.PropertyTypes)
        {
            if (known.Contains(seed.Name))
                continue;

            var type = Must(PropertyType.Create(seed.Name, seed.Description), $"PropertyType '{seed.Name}'");
            _db.PropertyTypes.Add(type);
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} property type(s).", added);
        }

        return await _db.PropertyTypes
            .ToDictionaryAsync(t => t.Name, t => t.Id, StringComparer.OrdinalIgnoreCase, ct);
    }

    // -----------------------------------------------------------------------------------------
    //  2. feature catalog
    // -----------------------------------------------------------------------------------------
    private async Task<Dictionary<string, Guid>> SeedFeaturesAsync(CancellationToken ct)
    {
        var existing = await _db.Features
            .Select(f => f.Name)
            .ToListAsync(ct);

        var known = new HashSet<string>(existing, StringComparer.OrdinalIgnoreCase);
        var added = 0;

        foreach (var seed in SeedCatalog.Features)
        {
            if (known.Contains(seed.Name))
                continue;

            var feature = Must(Feature.Create(seed.Name, seed.ValueType, seed.Icon), $"Feature '{seed.Name}'");
            _db.Features.Add(feature);
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} feature(s).", added);
        }

        return await _db.Features
            .ToDictionaryAsync(f => f.Name, f => f.Id, StringComparer.OrdinalIgnoreCase, ct);
    }

    // -----------------------------------------------------------------------------------------
    //  3. properties (aggregate root + owned Media + owned PropertyFeature links)
    // -----------------------------------------------------------------------------------------
    private async Task SeedPropertiesAsync(
        Dictionary<string, Guid> propertyTypeIds,
        Dictionary<string, Guid> featureIds,
        CancellationToken ct)
    {
        var existingTitles = new HashSet<string>(
            await _db.Properties.Select(p => p.Title).ToListAsync(ct),
            StringComparer.OrdinalIgnoreCase);

        var added = 0;

        foreach (var seed in SeedCatalog.Properties)
        {
            if (existingTitles.Contains(seed.Title))
                continue;

            if (!propertyTypeIds.TryGetValue(seed.PropertyTypeName, out var typeId))
                throw new InvalidOperationException(
                    $"Seed failed: listing '{seed.Title}' references property type " +
                    $"'{seed.PropertyTypeName}', which is not in SeedCatalog.PropertyTypes.");

            // The id must exist BEFORE the media is built: Media.Create rejects Guid.Empty.
            var propertyId = Guid.NewGuid();

            var location = Must(
                Location.Create(seed.Country, seed.City, seed.Street, seed.PostalCode,
                                seed.State, seed.Longitude, seed.Latitude, seed.LocationDescription),
                $"Location of '{seed.Title}'");

            var specs = new PropertySpecs
            {
                NumberOfRooms = seed.Rooms,
                Bathrooms = seed.Bathrooms,
                AreaInSquareMeters = seed.AreaInSquareMeters,
            };

            var sale = seed.Kind == ListingKind.Sale ? BuildSaleTerms(seed) : null;
            var rent = seed.Kind == ListingKind.Rent ? BuildRentTerms(seed) : null;

            var property = Must(
                Property.Create(propertyId, seed.Title, seed.Description, typeId,
                                location, seed.Kind, sale, rent, specs),
                $"Property '{seed.Title}'");

            // ---- media ----------------------------------------------------------------------
            if (seed.Media.Length > 0)
            {
                var media = seed.Media
                    .Select(m => Must(
                        Media.Create(m.Url, m.Kind, m.Width, m.Height, m.Order, m.IsPrimary, propertyId),
                        $"Media '{m.Url}' of '{seed.Title}'"))
                    .ToList();

                MustSucceed(property.AddMedia(media), $"adding media to '{seed.Title}'");
            }

            // ---- features -------------------------------------------------------------------
            if (seed.Features.Length > 0)
            {
                var links = seed.Features
                    .Select(f =>
                    {
                        if (!featureIds.TryGetValue(f.FeatureName, out var featureId))
                            throw new InvalidOperationException(
                                $"Seed failed: listing '{seed.Title}' references feature " +
                                $"'{f.FeatureName}', which is not in SeedCatalog.Features.");

                        return Must(PropertyFeature.Create(featureId, f.Value),
                                    $"Feature link '{f.FeatureName}' of '{seed.Title}'");
                    })
                    .ToList();

                MustSucceed(property.AddFeatures(links), $"adding features to '{seed.Title}'");
            }

            // ---- lifecycle ------------------------------------------------------------------
            // Every listing starts as Draft, so record that first, then the publish transition.
            _db.PropertyStatusHistories.Add(
                PropertyStatusHistory.Record(propertyId, null, PropertyStatus.Draft, "Seeded"));

            if (seed.Publish)
            {
                MustSucceed(property.Publish(), $"publishing '{seed.Title}'");

                _db.PropertyStatusHistories.Add(
                    PropertyStatusHistory.Record(propertyId, PropertyStatus.Draft,
                                                 PropertyStatus.Published, "Seeded"));

                // Property.Feature() refuses on anything that is not Published — hence the order.
                if (seed.IsFeatured)
                    MustSucceed(property.Feature(), $"featuring '{seed.Title}'");
            }
            else if (seed.IsFeatured)
            {
                throw new InvalidOperationException(
                    $"Seed failed: listing '{seed.Title}' is marked IsFeatured but not Publish. " +
                    "The domain only allows a published listing to be featured.");
            }

            _db.Properties.Add(property);
            existingTitles.Add(seed.Title);
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} propert(y/ies).", added);
        }
        else
        {
            _log?.LogInformation("Seed: nothing to do, all seed listings already exist.");
        }
    }

    // -----------------------------------------------------------------------------------------
    //  helpers
    // -----------------------------------------------------------------------------------------
    private static SaleTerms BuildSaleTerms(PropertySeed seed)
    {
        var price = Must(Money.Create(seed.SalePrice, seed.Currency), $"sale price of '{seed.Title}'");

        InstallmentPlan? plan = null;
        if (seed.PaymentMethod == PaymentMethod.Installment)
        {
            if (seed.Installment is null)
                throw new InvalidOperationException(
                    $"Seed failed: listing '{seed.Title}' uses PaymentMethod.Installment " +
                    "but has no Installment block in SeedCatalog.");

            var down = Must(Money.Create(seed.Installment.DownPayment, seed.Currency),
                            $"down payment of '{seed.Title}'");
            var each = Must(Money.Create(seed.Installment.InstallmentAmount, seed.Currency),
                            $"installment amount of '{seed.Title}'");

            plan = Must(
                InstallmentPlan.Create(down, seed.Installment.NumberOfInstallments, each,
                                       seed.Installment.Frequency),
                $"installment plan of '{seed.Title}'");
        }

        return Must(SaleTerms.Create(price, seed.PaymentMethod, plan), $"sale terms of '{seed.Title}'");
    }

    private static RentTerms BuildRentTerms(PropertySeed seed)
    {
        var price = Must(Money.Create(seed.RentPrice, seed.Currency), $"rent price of '{seed.Title}'");
        return Must(RentTerms.Create(price, seed.ContractDurationMonths), $"rent terms of '{seed.Title}'");
    }

    /// <summary>Unwraps a domain factory result or fails loudly — seed data must never be invalid.</summary>
    private static T Must<T>(Result<T> result, string what)
    {
        if (result.IsError)
        {
            var error = result.TopError;
            throw new InvalidOperationException(
                $"Seed failed building {what}: [{error.Code}] {error.Description}");
        }

        return result.Value;
    }

    private static void MustSucceed(Result<Updated> result, string what)
    {
        if (result.IsError)
        {
            var error = result.TopError;
            throw new InvalidOperationException(
                $"Seed failed while {what}: [{error.Code}] {error.Description}");
        }
    }
}
