using BuildingBlocks.Domain.Common.Results;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using RealEstate.Domain.Entities;
using RealEstate.Domain.Enums;
using RealEstate.Domain.ValueObjects;

namespace RealEstate.Infrastructure.Data.Seeding;

// ---------------------------------------------------------------------------------------------
//  Runtime seeder for the RealEstate module.
//
//  TWO BATCHES, SEEDED SEPARATELY — because they answer to different rules:
//
//    REFERENCE DATA (SeedReferenceDataAsync)
//        Property types and the feature/amenity catalog. The dropdowns an empty deployment
//        cannot function without.
//
//    DEMO DATA (SeedDemoDataAsync)
//        49 showcase listings, 12 invented consultants with invented phone numbers, 15 areas,
//        14 projects, 6 job adverts. Sales material for a walkthrough. NEVER production data.
//
//  RUN ONCE, NOT "INSERT WHAT IS MISSING".
//    This seeder used to compare rows: for each catalog entry, look for it and insert it if it
//    was not there. On a fresh database that is right. On a live one it makes deletion
//    impossible — a listing the admin deleted is exactly a row the next restart puts back, and
//    that is the bug this file was rewritten to fix.
//
//    Each batch now records itself in realestate.SeedHistory when it finishes, and a batch that
//    is already recorded does not run at all. What the admin does to those rows afterwards —
//    edit, delete, archive — is final. To ship NEW reference data later, add it under a new key
//    (reference-data-v2): the old key stays applied and nothing deleted comes back.
//
//  WHY RUNTIME AND NOT modelBuilder.HasData(...)
//    HasData bakes rows into a migration and cannot call the domain factories, so it would
//    write rows that bypass every invariant in Property/Media/Location. This goes through the
//    real aggregates, so seeded data is exactly as valid as data created through the API.
//
//  ORDER MATTERS: Feature/PropertyType/Area/Agent ids are generated by EF on insert, so they
//  are Guid.Empty in memory until SaveChanges runs. Each catalog is saved before anything can
//  reference it.
// ---------------------------------------------------------------------------------------------

public sealed class RealEstateDbSeeder
{
    private readonly RealEstateDbContext _db;
    private readonly ILogger? _log;
    private readonly TimeProvider _clock;

    public RealEstateDbSeeder(RealEstateDbContext db, ILogger? log = null, TimeProvider? clock = null)
    {
        _db = db;
        _log = log;
        _clock = clock ?? TimeProvider.System;
    }

    /// <summary>
    /// Property types + the feature catalog. Safe on a production database: it is the reference
    /// data the admin forms are built from, and it carries no invented people or listings.
    /// </summary>
    public async Task<bool> SeedReferenceDataAsync(bool force = false, CancellationToken ct = default)
    {
        if (!await ShouldRunAsync(SeedHistoryEntry.ReferenceDataKey, force, ct))
            return false;

        await SeedPropertyTypesAsync(ct);
        await SeedFeaturesAsync(ct);

        await RecordAsync(SeedHistoryEntry.ReferenceDataKey, "Property types and feature catalog.", ct);
        return true;
    }

    /// <summary>
    /// The demo content: showcase listings, consultants, areas, projects and job adverts.
    /// Development and testing only — see SeedCommand for the production guard that keeps this
    /// off the live site.
    /// </summary>
    public async Task<bool> SeedDemoDataAsync(bool force = false, CancellationToken ct = default)
    {
        if (!await ShouldRunAsync(SeedHistoryEntry.DemoDataKey, force, ct))
            return false;

        // Demo listings reference the reference catalogs by NAME, so those have to exist first.
        // They may already be applied from an earlier run — read them back either way.
        var propertyTypeIds = await SeedPropertyTypesAsync(ct);
        var featureIds = await SeedFeaturesAsync(ct);

        // Areas and agents run BEFORE properties: showcase listings name their area and their
        // consultant by slug, and the backfills below need both rosters to exist.
        await SeedAreasAsync(ct);
        await SeedAgentsAsync(ct);

        var seededTitles = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        seededTitles.UnionWith(await SeedPropertiesAsync(propertyTypeIds, featureIds, ct));
        seededTitles.UnionWith(await SeedShowcasePropertiesAsync(propertyTypeIds, featureIds, ct));

        // The two backfills below are DEMO-DATA REPAIRS, and they are restricted to the listings
        // this run just inserted. They used to run over the whole table on every startup, which
        // meant a real listing an admin had deliberately left without an area or a consultant
        // was quietly given a made-up one — the site then showed a customer an invented agent's
        // phone number. Scoping them to the rows we just created keeps the demo content
        // complete without ever touching the brokerage's own data.
        await BackfillSeededPropertyAreasAsync(seededTitles, ct);
        await BackfillSeededPropertyAgentsAsync(seededTitles, ct);

        await SeedDevelopmentsAsync(ct);
        await SeedJobsAsync(ct);

        await RecordAsync(SeedHistoryEntry.DemoDataKey, "Demo listings, agents, areas, developments and jobs.", ct);
        return true;
    }

    // -----------------------------------------------------------------------------------------
    //  the ledger
    // -----------------------------------------------------------------------------------------

    private async Task<bool> ShouldRunAsync(string key, bool force, CancellationToken ct)
    {
        var existing = await _db.SeedHistory.FirstOrDefaultAsync(e => e.Key == key, ct);

        if (existing is null)
            return true;

        if (!force)
        {
            _log?.LogInformation(
                "Seed: batch '{Key}' was already applied on {AppliedAt:u} — skipping. " +
                "Rows deleted or edited since then are left alone, which is the point.",
                key, existing.AppliedAtUtc);
            return false;
        }

        // --force is the deliberate escape hatch for a dev machine or a fresh test database:
        // drop the record so the batch runs again and re-inserts whatever is missing.
        _log?.LogWarning("Seed: batch '{Key}' is being FORCED to run again. Deleted rows will come back.", key);
        _db.SeedHistory.Remove(existing);
        await _db.SaveChangesAsync(ct);
        return true;
    }

    private async Task RecordAsync(string key, string note, CancellationToken ct)
    {
        _db.SeedHistory.Add(SeedHistoryEntry.Record(key, _clock.GetUtcNow(), note));
        await _db.SaveChangesAsync(ct);
        _log?.LogInformation("Seed: batch '{Key}' applied and recorded.", key);
    }

    // -----------------------------------------------------------------------------------------
    //  jobs  (matched on Title — NOT uniquely indexed, so this check is application-level only)
    // -----------------------------------------------------------------------------------------
    private async Task SeedJobsAsync(CancellationToken ct)
    {
        var existing = await _db.Jobs.Select(j => j.Title).ToListAsync(ct);
        var known = new HashSet<string>(existing, StringComparer.OrdinalIgnoreCase);
        var added = 0;

        foreach (var seed in JobSeedCatalog.Jobs)
        {
            if (known.Contains(seed.Title))
                continue;

            var job = Must(
                Job.Create(seed.Title, seed.Department, seed.EmploymentType,
                           seed.Location, seed.Description),
                $"Job '{seed.Title}'");

            _db.Jobs.Add(job);
            known.Add(seed.Title);      // guards against a duplicate title inside the catalog itself
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} job opening(s).", added);
        }
    }

    // -----------------------------------------------------------------------------------------
    //  areas  (matched on Slug — uniquely indexed, so this check is DB-backed)
    // -----------------------------------------------------------------------------------------
    private async Task SeedAreasAsync(CancellationToken ct)
    {
        var existing = await _db.Areas.Select(a => a.Slug).ToListAsync(ct);
        var known = new HashSet<string>(existing, StringComparer.Ordinal);
        var added = 0;

        foreach (var seed in AreaSeedCatalog.Areas.Concat(ShowcaseSeedCatalog.Areas))
        {
            if (known.Contains(seed.Slug))
                continue;

            var area = Must(
                Area.Create(seed.Name, seed.PhotoUrl, seed.Slug, seed.Intro),
                $"Area '{seed.Name}'");

            _db.Areas.Add(area);
            known.Add(seed.Slug);       // guards against a duplicate slug across the two catalogs
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} area(s).", added);
        }
    }

    // -----------------------------------------------------------------------------------------
    //  Files the listings THIS RUN just inserted under an area, by keyword.
    //
    //  Scoped to `seededTitles` on purpose: see the note at the call site. A listing created
    //  through the admin panel is never touched by this, whatever its AreaId is.
    // -----------------------------------------------------------------------------------------
    private async Task BackfillSeededPropertyAreasAsync(
        IReadOnlySet<string> seededTitles, CancellationToken ct)
    {
        if (seededTitles.Count == 0)
            return;

        var titles = seededTitles.ToList();
        var unfiled = await _db.Properties
            .Where(p => p.AreaId == null && titles.Contains(p.Title))
            .ToListAsync(ct);

        if (unfiled.Count == 0)
            return;

        var areaIdsBySlug = await _db.Areas.ToDictionaryAsync(a => a.Slug, a => a.Id, StringComparer.Ordinal, ct);
        var filed = 0;

        foreach (var property in unfiled)
        {
            var haystack = $"{property.Title} {property.Location.StreetName}";

            foreach (var (slug, keywords) in AreaSeedCatalog.BackfillKeywords)
            {
                if (!keywords.Any(k => haystack.Contains(k, StringComparison.OrdinalIgnoreCase)))
                    continue;

                if (!areaIdsBySlug.TryGetValue(slug, out var areaId))
                    break;      // area was deleted by an admin — leave the listing unfiled

                MustSucceed(property.AssignArea(areaId), $"filing '{property.Title}' under '{slug}'");
                filed++;
                break;          // first match wins — see AreaSeedCatalog.BackfillKeywords
            }
        }

        if (filed > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: filed {Count} seeded listing(s) under an area.", filed);
        }
    }

    // -----------------------------------------------------------------------------------------
    //  Gives the listings THIS RUN just inserted a consultant, spread across the active roster.
    //
    //  Why it exists: PropertySeed (the original catalog) carries no agent, so those demo
    //  listings would render a card with no "Listed by" block. The pick is deterministic — a
    //  stable character hash of the title, NOT string.GetHashCode (randomised per process) and
    //  NOT Random (different every run).
    //
    //  Scoped to `seededTitles`: a real listing the admin left unassigned keeps no agent rather
    //  than being given an invented one whose phone number a customer would then call.
    // -----------------------------------------------------------------------------------------
    private async Task BackfillSeededPropertyAgentsAsync(
        IReadOnlySet<string> seededTitles, CancellationToken ct)
    {
        if (seededTitles.Count == 0)
            return;

        var titles = seededTitles.ToList();
        var unassigned = await _db.Properties
            .Where(p => p.AgentId == null && titles.Contains(p.Title))
            .ToListAsync(ct);

        if (unassigned.Count == 0)
            return;

        // Ordered by slug so the roster order is stable regardless of insert order.
        var agentIds = await _db.Agents
            .Where(a => a.IsActive)
            .OrderBy(a => a.Slug)
            .Select(a => a.Id)
            .ToListAsync(ct);

        if (agentIds.Count == 0)
        {
            _log?.LogInformation("Seed: no active agents, leaving {Count} listing(s) unassigned.", unassigned.Count);
            return;
        }

        var assigned = 0;
        foreach (var property in unassigned)
        {
            var agentId = agentIds[StableIndex(property.Title, agentIds.Count)];
            MustSucceed(property.AssignAgent(agentId), $"assigning an agent to '{property.Title}'");
            assigned++;
        }

        if (assigned > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: assigned a consultant to {Count} seeded listing(s).", assigned);
        }
    }

    // -----------------------------------------------------------------------------------------
    //  developments  (matched on Slug — uniquely indexed, so this check is DB-backed)
    //
    //  NOTE: this used to also "refresh" the cover image of every development the catalog knew,
    //  overwriting whatever photo the admin had chosen, on every single startup. That block is
    //  gone: the catalog seeds a project once, and the photography belongs to the admin panel
    //  from that moment on.
    // -----------------------------------------------------------------------------------------
    private async Task SeedDevelopmentsAsync(CancellationToken ct)
    {
        var catalog = DevelopmentSeedCatalog.Developments
            .Concat(ShowcaseSeedCatalog.Developments)
            .ToList();

        var existing = await _db.Developments.Select(d => d.Slug).ToListAsync(ct);
        var known = new HashSet<string>(existing, StringComparer.Ordinal);
        var added = 0;

        foreach (var seed in catalog)
        {
            if (known.Contains(seed.Slug))
                continue;

            // X = longitude, Y = latitude, invariant culture — same convention as Property.
            var location = Must(
                Domain.ValueObjects.Location.Create(
                    "Qatar", "Doha", seed.Area, "00000", seed.Area,
                    seed.Lng.ToString(System.Globalization.CultureInfo.InvariantCulture),
                    seed.Lat.ToString(System.Globalization.CultureInfo.InvariantCulture)),
                $"Development location '{seed.Name}'");

            var development = Must(
                Development.Create(seed.Name, location, seed.DeliveryYear, seed.CoverImageUrl,
                                   seed.Slug, seed.Description, seed.UnitsCount, seed.DeveloperName,
                                   seed.StartingPrice, seed.PaymentPlan),
                $"Development '{seed.Name}'");

            _db.Developments.Add(development);
            known.Add(seed.Slug);       // guards against a duplicate slug across the two catalogs
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} development(s).", added);
        }
    }

    // -----------------------------------------------------------------------------------------
    //  agents  (matched on Slug — uniquely indexed, so this check is DB-backed)
    // -----------------------------------------------------------------------------------------
    private async Task SeedAgentsAsync(CancellationToken ct)
    {
        var existing = await _db.Agents.Select(a => a.Slug).ToListAsync(ct);
        var known = new HashSet<string>(existing, StringComparer.Ordinal);
        var added = 0;

        foreach (var seed in AgentSeedCatalog.Agents)
        {
            if (known.Contains(seed.Slug))
                continue;

            var agent = Must(
                Agent.Create(seed.Name, seed.JobTitle, seed.PhotoUrl, seed.Slug,
                             seed.Phone, seed.WhatsApp, seed.Email, seed.Rating, seed.Bio),
                $"Agent '{seed.Name}'");

            _db.Agents.Add(agent);
            known.Add(seed.Slug);
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} agent(s).", added);
        }
    }

    // -----------------------------------------------------------------------------------------
    //  1. property types
    // -----------------------------------------------------------------------------------------
    private async Task<Dictionary<string, Guid>> SeedPropertyTypesAsync(CancellationToken ct)
    {
        var existing = await _db.PropertyTypes
            .Select(t => t.Name)
            .ToListAsync(ct);

        var known = new HashSet<string>(existing, StringComparer.OrdinalIgnoreCase);
        var added = 0;

        foreach (var seed in SeedCatalog.PropertyTypes.Concat(ShowcaseSeedCatalog.PropertyTypes))
        {
            if (known.Contains(seed.Name))
                continue;

            var type = Must(PropertyType.Create(seed.Name, seed.Description), $"PropertyType '{seed.Name}'");
            _db.PropertyTypes.Add(type);
            known.Add(seed.Name);       // guards against a duplicate name across the two catalogs
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} property type(s).", added);
        }

        return await _db.PropertyTypes
            .ToDictionaryAsync(t => t.Name, t => t.Id, StringComparer.OrdinalIgnoreCase, ct);
    }

    // -----------------------------------------------------------------------------------------
    //  2. feature catalog
    // -----------------------------------------------------------------------------------------
    private async Task<Dictionary<string, Guid>> SeedFeaturesAsync(CancellationToken ct)
    {
        var existing = await _db.Features
            .Select(f => f.Name)
            .ToListAsync(ct);

        var known = new HashSet<string>(existing, StringComparer.OrdinalIgnoreCase);
        var added = 0;

        foreach (var seed in SeedCatalog.Features)
        {
            if (known.Contains(seed.Name))
                continue;

            var feature = Must(Feature.Create(seed.Name, seed.ValueType, seed.Icon), $"Feature '{seed.Name}'");
            _db.Features.Add(feature);
            known.Add(seed.Name);
            added++;
        }

        if (added > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} feature(s).", added);
        }

        return await _db.Features
            .ToDictionaryAsync(f => f.Name, f => f.Id, StringComparer.OrdinalIgnoreCase, ct);
    }

    // -----------------------------------------------------------------------------------------
    //  3. properties (aggregate root + owned Media + owned PropertyFeature links)
    //
    //  Returns the titles it actually inserted, so the backfills can scope themselves to them.
    // -----------------------------------------------------------------------------------------
    private async Task<IReadOnlyCollection<string>> SeedPropertiesAsync(
        Dictionary<string, Guid> propertyTypeIds,
        Dictionary<string, Guid> featureIds,
        CancellationToken ct)
    {
        var existingTitles = new HashSet<string>(
            await _db.Properties.Select(p => p.Title).ToListAsync(ct),
            StringComparer.OrdinalIgnoreCase);

        var inserted = new List<string>();

        foreach (var seed in SeedCatalog.Properties)
        {
            if (existingTitles.Contains(seed.Title))
                continue;

            if (!propertyTypeIds.TryGetValue(seed.PropertyTypeName, out var typeId))
                throw new InvalidOperationException(
                    $"Seed failed: listing '{seed.Title}' references property type " +
                    $"'{seed.PropertyTypeName}', which is not in SeedCatalog.PropertyTypes.");

            // The id must exist BEFORE the media is built: Media.Create rejects Guid.Empty.
            var propertyId = Guid.NewGuid();

            var location = Must(
                Location.Create(seed.Country, seed.City, seed.Street, seed.PostalCode,
                                seed.State, seed.Longitude, seed.Latitude, seed.LocationDescription),
                $"Location of '{seed.Title}'");

            var specs = new PropertySpecs
            {
                NumberOfRooms = seed.Rooms,
                Bathrooms = seed.Bathrooms,
                AreaInSquareMeters = seed.AreaInSquareMeters,
            };

            var sale = seed.Kind == ListingKind.Sale
                ? BuildSaleTerms(seed.Title, seed.SalePrice, seed.Currency, seed.PaymentMethod, seed.Installment)
                : null;
            var rent = seed.Kind == ListingKind.Rent
                ? BuildRentTerms(seed.Title, seed.RentPrice, seed.Currency, seed.ContractDurationMonths)
                : null;

            var property = Must(
                Property.Create(propertyId, seed.Title, seed.Description, typeId,
                                location, seed.Kind, sale, rent, specs),
                $"Property '{seed.Title}'");

            // ---- media ----------------------------------------------------------------------
            if (seed.Media.Length > 0)
            {
                var media = seed.Media
                    .Select(m => Must(
                        Media.Create(m.Url, m.Kind, m.Width, m.Height, m.Order, m.IsPrimary, propertyId),
                        $"Media '{m.Url}' of '{seed.Title}'"))
                    .ToList();

                MustSucceed(property.AddMedia(media), $"adding media to '{seed.Title}'");
            }

            // ---- features -------------------------------------------------------------------
            if (seed.Features.Length > 0)
            {
                var links = seed.Features
                    .Select(f =>
                    {
                        if (!featureIds.TryGetValue(f.FeatureName, out var featureId))
                            throw new InvalidOperationException(
                                $"Seed failed: listing '{seed.Title}' references feature " +
                                $"'{f.FeatureName}', which is not in SeedCatalog.Features.");

                        return Must(PropertyFeature.Create(featureId, f.Value),
                                    $"Feature link '{f.FeatureName}' of '{seed.Title}'");
                    })
                    .ToList();

                MustSucceed(property.AddFeatures(links), $"adding features to '{seed.Title}'");
            }

            // ---- lifecycle ------------------------------------------------------------------
            // Every listing starts as Draft, so record that first, then the publish transition.
            _db.PropertyStatusHistories.Add(
                PropertyStatusHistory.Record(propertyId, null, PropertyStatus.Draft, "Seeded"));

            if (seed.Publish)
            {
                MustSucceed(property.Publish(), $"publishing '{seed.Title}'");

                _db.PropertyStatusHistories.Add(
                    PropertyStatusHistory.Record(propertyId, PropertyStatus.Draft,
                                                 PropertyStatus.Published, "Seeded"));

                // Property.Feature() refuses on anything that is not Published — hence the order.
                if (seed.IsFeatured)
                    MustSucceed(property.Feature(), $"featuring '{seed.Title}'");
            }
            else if (seed.IsFeatured)
            {
                throw new InvalidOperationException(
                    $"Seed failed: listing '{seed.Title}' is marked IsFeatured but not Publish. " +
                    "The domain only allows a published listing to be featured.");
            }

            _db.Properties.Add(property);
            existingTitles.Add(seed.Title);
            inserted.Add(seed.Title);
        }

        if (inserted.Count > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} propert(y/ies).", inserted.Count);
        }
        else
        {
            _log?.LogInformation("Seed: nothing to do, all seed listings already exist.");
        }

        return inserted;
    }

    // -----------------------------------------------------------------------------------------
    //  4. showcase properties (ShowcaseSeedCatalog)
    //
    //  Same aggregate construction as SeedPropertiesAsync, plus the four things a
    //  ShowcasePropertySeed carries that a PropertySeed does not: an explicit AreaSlug and
    //  AgentSlug, and the IsOffPlan / PriceOnRequest flags.
    // -----------------------------------------------------------------------------------------
    private async Task<IReadOnlyCollection<string>> SeedShowcasePropertiesAsync(
        Dictionary<string, Guid> propertyTypeIds,
        Dictionary<string, Guid> featureIds,
        CancellationToken ct)
    {
        var existingTitles = new HashSet<string>(
            await _db.Properties.Select(p => p.Title).ToListAsync(ct),
            StringComparer.OrdinalIgnoreCase);

        var areaIdsBySlug = await _db.Areas
            .ToDictionaryAsync(a => a.Slug, a => a.Id, StringComparer.Ordinal, ct);
        var agentIdsBySlug = await _db.Agents
            .ToDictionaryAsync(a => a.Slug, a => a.Id, StringComparer.Ordinal, ct);

        var inserted = new List<string>();

        foreach (var seed in ShowcaseSeedCatalog.Properties)
        {
            if (existingTitles.Contains(seed.Title))
                continue;

            if (!propertyTypeIds.TryGetValue(seed.PropertyTypeName, out var typeId))
                throw new InvalidOperationException(
                    $"Seed failed: showcase listing '{seed.Title}' references property type " +
                    $"'{seed.PropertyTypeName}', which is in neither SeedCatalog.PropertyTypes " +
                    "nor ShowcaseSeedCatalog.PropertyTypes.");

            // The id must exist BEFORE the media is built: Media.Create rejects Guid.Empty.
            var propertyId = Guid.NewGuid();

            var location = Must(
                Location.Create(seed.Country, seed.City, seed.Street, seed.PostalCode,
                                seed.State, seed.Longitude, seed.Latitude, seed.LocationDescription),
                $"Location of '{seed.Title}'");

            var specs = new PropertySpecs
            {
                NumberOfRooms = seed.Rooms,
                Bathrooms = seed.Bathrooms,
                AreaInSquareMeters = seed.AreaInSquareMeters,
            };

            var sale = seed.Kind == ListingKind.Sale
                ? BuildSaleTerms(seed.Title, seed.SalePrice, seed.Currency, seed.PaymentMethod, seed.Installment)
                : null;
            var rent = seed.Kind == ListingKind.Rent
                ? BuildRentTerms(seed.Title, seed.RentPrice, seed.Currency, seed.ContractDurationMonths)
                : null;

            var property = Must(
                Property.Create(propertyId, seed.Title, seed.Description, typeId,
                                location, seed.Kind, sale, rent, specs),
                $"Showcase property '{seed.Title}'");

            // ---- media ----------------------------------------------------------------------
            if (seed.Media.Length > 0)
            {
                var media = seed.Media
                    .Select(m => Must(
                        Media.Create(m.Url, m.Kind, m.Width, m.Height, m.Order, m.IsPrimary, propertyId),
                        $"Media '{m.Url}' of '{seed.Title}'"))
                    .ToList();

                MustSucceed(property.AddMedia(media), $"adding media to '{seed.Title}'");
            }

            // ---- features -------------------------------------------------------------------
            if (seed.Features.Length > 0)
            {
                var links = seed.Features
                    .Select(f =>
                    {
                        if (!featureIds.TryGetValue(f.FeatureName, out var featureId))
                            throw new InvalidOperationException(
                                $"Seed failed: showcase listing '{seed.Title}' references feature " +
                                $"'{f.FeatureName}', which is not in SeedCatalog.Features.");

                        return Must(PropertyFeature.Create(featureId, f.Value),
                                    $"Feature link '{f.FeatureName}' of '{seed.Title}'");
                    })
                    .ToList();

                MustSucceed(property.AddFeatures(links), $"adding features to '{seed.Title}'");
            }

            // ---- catalog links --------------------------------------------------------------
            if (!string.IsNullOrWhiteSpace(seed.AreaSlug))
            {
                if (areaIdsBySlug.TryGetValue(seed.AreaSlug, out var areaId))
                    MustSucceed(property.AssignArea(areaId), $"filing '{seed.Title}' under '{seed.AreaSlug}'");
                else
                    _log?.LogWarning("Seed: area '{Slug}' not found — '{Title}' left unfiled.",
                                     seed.AreaSlug, seed.Title);
            }

            if (!string.IsNullOrWhiteSpace(seed.AgentSlug))
            {
                if (agentIdsBySlug.TryGetValue(seed.AgentSlug, out var agentId))
                    MustSucceed(property.AssignAgent(agentId), $"assigning '{seed.AgentSlug}' to '{seed.Title}'");
                else
                    _log?.LogWarning("Seed: agent '{Slug}' not found — '{Title}' left unassigned.",
                                     seed.AgentSlug, seed.Title);
            }

            // ---- flags ----------------------------------------------------------------------
            // Neither of these has a status guard, so order against Publish does not matter.
            if (seed.IsOffPlan)
                MustSucceed(property.MarkOffPlan(), $"marking '{seed.Title}' off-plan");

            if (seed.PriceOnRequest)
                MustSucceed(property.MarkPriceOnRequest(), $"hiding the price of '{seed.Title}'");

            // ---- lifecycle ------------------------------------------------------------------
            _db.PropertyStatusHistories.Add(
                PropertyStatusHistory.Record(propertyId, null, PropertyStatus.Draft, "Seeded"));

            if (seed.Publish)
            {
                MustSucceed(property.Publish(), $"publishing '{seed.Title}'");

                _db.PropertyStatusHistories.Add(
                    PropertyStatusHistory.Record(propertyId, PropertyStatus.Draft,
                                                 PropertyStatus.Published, "Seeded"));

                // Property.Feature() refuses on anything that is not Published — hence the order.
                if (seed.IsFeatured)
                    MustSucceed(property.Feature(), $"featuring '{seed.Title}'");
            }
            else if (seed.IsFeatured)
            {
                throw new InvalidOperationException(
                    $"Seed failed: showcase listing '{seed.Title}' is marked IsFeatured but not " +
                    "Publish. The domain only allows a published listing to be featured.");
            }

            _db.Properties.Add(property);
            existingTitles.Add(seed.Title);
            inserted.Add(seed.Title);
        }

        if (inserted.Count > 0)
        {
            await _db.SaveChangesAsync(ct);
            _log?.LogInformation("Seed: inserted {Count} showcase listing(s).", inserted.Count);
        }
        else
        {
            _log?.LogInformation("Seed: nothing to do, all showcase listings already exist.");
        }

        return inserted;
    }

    // -----------------------------------------------------------------------------------------
    //  helpers
    // -----------------------------------------------------------------------------------------

    /// <summary>
    /// Deterministic, process-stable index into a list. Deliberately NOT string.GetHashCode:
    /// that is randomised per process, so the same title would map to a different agent on
    /// every restart.
    /// </summary>
    private static int StableIndex(string value, int modulo)
    {
        unchecked
        {
            var hash = 17;
            foreach (var ch in value)
                hash = (hash * 31) + ch;

            return (hash & 0x7FFFFFFF) % modulo;
        }
    }

    private static SaleTerms BuildSaleTerms(
        string title, decimal salePrice, string currency,
        PaymentMethod paymentMethod, InstallmentSeed? installment)
    {
        var price = Must(Money.Create(salePrice, currency), $"sale price of '{title}'");

        InstallmentPlan? plan = null;
        if (paymentMethod == PaymentMethod.Installment)
        {
            if (installment is null)
                throw new InvalidOperationException(
                    $"Seed failed: listing '{title}' uses PaymentMethod.Installment " +
                    "but has no Installment block in its seed catalog.");

            var down = Must(Money.Create(installment.DownPayment, currency),
                            $"down payment of '{title}'");
            var each = Must(Money.Create(installment.InstallmentAmount, currency),
                            $"installment amount of '{title}'");

            plan = Must(
                InstallmentPlan.Create(down, installment.NumberOfInstallments, each,
                                       installment.Frequency),
                $"installment plan of '{title}'");
        }

        return Must(SaleTerms.Create(price, paymentMethod, plan), $"sale terms of '{title}'");
    }

    private static RentTerms BuildRentTerms(
        string title, decimal rentPrice, string currency, int contractDurationMonths)
    {
        var price = Must(Money.Create(rentPrice, currency), $"rent price of '{title}'");
        return Must(RentTerms.Create(price, contractDurationMonths), $"rent terms of '{title}'");
    }

    /// <summary>Unwraps a domain factory result or fails loudly — seed data must never be invalid.</summary>
    private static T Must<T>(Result<T> result, string what)
    {
        if (result.IsError)
        {
            var error = result.TopError;
            throw new InvalidOperationException(
                $"Seed failed building {what}: [{error.Code}] {error.Description}");
        }

        return result.Value;
    }

    private static void MustSucceed(Result<Updated> result, string what)
    {
        if (result.IsError)
        {
            var error = result.TopError;
            throw new InvalidOperationException(
                $"Seed failed while {what}: [{error.Code}] {error.Description}");
        }
    }
}
