// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RealEstate.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    partial class RealEstateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("realestate")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstate.Domain.Entities.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Features_Name");

                    b.ToTable("Features", "realestate");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("PropertyId", "IsPrimary")
                        .HasDatabaseName("IX_Media_PrimaryPerProperty");

                    b.ToTable("PropertyMedia", "realestate");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ListingKind")
                        .HasColumnType("int");

                    b.Property<Guid>("PropertyTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ViewsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Properties_Owner");

                    b.HasIndex("PropertyTypeId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Properties_Status");

                    b.HasIndex("Status", "IsFeatured")
                        .HasDatabaseName("IX_Properties_Featured");

                    b.ToTable("Properties", "realestate");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.PropertyFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("PropertyId", "FeatureId")
                        .IsUnique()
                        .HasDatabaseName("UX_PropertyFeature_NoDuplicates");

                    b.ToTable("PropertyFeatures", "realestate");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.PropertyStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyStatusHistory", "realestate");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.PropertyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PropertyTypes", "realestate");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.Media", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.Property", null)
                        .WithMany("Media")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.Property", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.PropertyType", null)
                        .WithMany()
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("RealEstate.Domain.ValueObjects.Money", "Offer", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Offer_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Offer_Currency");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties", "realestate");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("RealEstate.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_City");

                            b1.Property<string>("CountryName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_Country");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Location_Description");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Location_PostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_State");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Location_Street");

                            b1.Property<string>("XCoordinate")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Location_X");

                            b1.Property<string>("YCoordinate")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Location_Y");

                            b1.HasKey("PropertyId");

                            b1.HasIndex("CityName")
                                .HasDatabaseName("IX_Properties_City");

                            b1.ToTable("Properties", "realestate");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("RealEstate.Domain.ValueObjects.PropertySpecs", "PropertySpecs", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AreaInSquareMeters")
                                .HasPrecision(12, 2)
                                .HasColumnType("decimal(12,2)")
                                .HasColumnName("Specs_Area");

                            b1.Property<int>("Bathrooms")
                                .HasColumnType("int")
                                .HasColumnName("Specs_Bathrooms");

                            b1.Property<int>("NumberOfRooms")
                                .HasColumnType("int")
                                .HasColumnName("Specs_Rooms");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties", "realestate");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("RealEstate.Domain.ValueObjects.RentTerms", "RentTerms", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ContractDurationMonths")
                                .HasColumnType("int")
                                .HasColumnName("Rent_DurationMonths");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties", "realestate");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");

                            b1.OwnsOne("RealEstate.Domain.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("RentTermsPropertyId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Rent_Price");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("Rent_Currency");

                                    b2.HasKey("RentTermsPropertyId");

                                    b2.ToTable("Properties", "realestate");

                                    b2.WithOwner()
                                        .HasForeignKey("RentTermsPropertyId");
                                });

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.OwnsOne("RealEstate.Domain.ValueObjects.SaleTerms", "SaleTerms", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("PaymentMethod")
                                .HasColumnType("int")
                                .HasColumnName("Sale_PaymentMethod");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties", "realestate");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");

                            b1.OwnsOne("RealEstate.Domain.ValueObjects.InstallmentPlan", "InstallmentPlan", b2 =>
                                {
                                    b2.Property<Guid>("SaleTermsPropertyId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Frequency")
                                        .HasColumnType("int")
                                        .HasColumnName("Inst_Frequency");

                                    b2.Property<int>("NumberOfInstallments")
                                        .HasColumnType("int")
                                        .HasColumnName("Inst_Count");

                                    b2.HasKey("SaleTermsPropertyId");

                                    b2.ToTable("Properties", "realestate");

                                    b2.WithOwner()
                                        .HasForeignKey("SaleTermsPropertyId");

                                    b2.OwnsOne("RealEstate.Domain.ValueObjects.Money", "DownPayment", b3 =>
                                        {
                                            b3.Property<Guid>("InstallmentPlanSaleTermsPropertyId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 2)
                                                .HasColumnType("decimal(18,2)")
                                                .HasColumnName("Inst_DownPayment");

                                            b3.Property<string>("Currency")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("nvarchar(3)")
                                                .HasColumnName("Inst_DownPayment_Currency");

                                            b3.HasKey("InstallmentPlanSaleTermsPropertyId");

                                            b3.ToTable("Properties", "realestate");

                                            b3.WithOwner()
                                                .HasForeignKey("InstallmentPlanSaleTermsPropertyId");
                                        });

                                    b2.OwnsOne("RealEstate.Domain.ValueObjects.Money", "InstallmentAmount", b3 =>
                                        {
                                            b3.Property<Guid>("InstallmentPlanSaleTermsPropertyId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<decimal>("Amount")
                                                .HasPrecision(18, 2)
                                                .HasColumnType("decimal(18,2)")
                                                .HasColumnName("Inst_Amount");

                                            b3.Property<string>("Currency")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("nvarchar(3)")
                                                .HasColumnName("Inst_Amount_Currency");

                                            b3.HasKey("InstallmentPlanSaleTermsPropertyId");

                                            b3.ToTable("Properties", "realestate");

                                            b3.WithOwner()
                                                .HasForeignKey("InstallmentPlanSaleTermsPropertyId");
                                        });

                                    b2.Navigation("DownPayment")
                                        .IsRequired();

                                    b2.Navigation("InstallmentAmount")
                                        .IsRequired();
                                });

                            b1.OwnsOne("RealEstate.Domain.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("SaleTermsPropertyId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Sale_Price");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("Sale_Currency");

                                    b2.HasKey("SaleTermsPropertyId");

                                    b2.ToTable("Properties", "realestate");

                                    b2.WithOwner()
                                        .HasForeignKey("SaleTermsPropertyId");
                                });

                            b1.Navigation("InstallmentPlan");

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("PropertySpecs")
                        .IsRequired();

                    b.Navigation("RentTerms");

                    b.Navigation("SaleTerms");
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.PropertyFeature", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealEstate.Domain.Entities.Property", null)
                        .WithMany("PropertyFeatures")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.PropertyStatusHistory", b =>
                {
                    b.HasOne("RealEstate.Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstate.Domain.Entities.Property", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("PropertyFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
